/*
 * Copyright (C) 2009-2014 SAP SE or an SAP affiliate company. All rights reserved
 */
jQuery.sap.declare("i2d.pp.prdorderissue.monitor.util.Formatter");jQuery.sap.require("sap.ca.ui.model.format.DateFormat");jQuery.sap.require("sap.ca.ui.model.format.QuantityFormat");jQuery.sap.require("i2d.pp.mrpcockpit.reuse.util.CommonFormatter");i2d.pp.prdorderissue.monitor.util.Formatter={};i2d.pp.prdorderissue.monitor.util.Formatter.oResourceBundle=null;
i2d.pp.prdorderissue.monitor.util.Formatter.getBundle=function(){if(i2d.pp.prdorderissue.monitor.util.Formatter.oResourceBundle){return i2d.pp.prdorderissue.monitor.util.Formatter.oResourceBundle}return{getText:function(a,b){return"ERROR"}}};
i2d.pp.prdorderissue.monitor.util.Formatter.formatDateShort=function(d){if(d){var D=sap.ca.ui.model.format.DateFormat.getDateInstance({style:"short"});return D.format(d)};return""};
i2d.pp.prdorderissue.monitor.util.Formatter.formatQuantity=function(v,p,u){if((v!=null)&&(p!=null)&&(u!=null)){var f=sap.ca.ui.model.format.QuantityFormat.FormatQuantityStandard(v,u,p);return f+" "+u};return""};
i2d.pp.prdorderissue.monitor.util.Formatter.formatDelay=function(d){if(d){if(d===1){return i2d.pp.prdorderissue.monitor.util.Formatter.getBundle().getText("Day",[d])}if((d>1)&&(d!==999)){return i2d.pp.prdorderissue.monitor.util.Formatter.getBundle().getText("Days",[d])}if((d<=0)||(d===999)){return""}};return""};
i2d.pp.prdorderissue.monitor.util.Formatter.formatComponentDelay=function(d){if(d){if(d===1){return i2d.pp.prdorderissue.monitor.util.Formatter.getBundle().getText("Day",[d])}if((d>1)&&(d!==999)){return i2d.pp.prdorderissue.monitor.util.Formatter.getBundle().getText("Days",[d])}if(d===999){return i2d.pp.prdorderissue.monitor.util.Formatter.getBundle().getText("NoSupply")};if(d<=0){return""}};return""};
i2d.pp.prdorderissue.monitor.util.Formatter.formatIcon=function(c){switch(c){case false:return"";break;case true:return"sap-icon://accept";break;default:return""}};
i2d.pp.prdorderissue.monitor.util.Formatter.pdaTooltip=function(c){switch(c){case false:return"";break;case true:return i2d.pp.prdorderissue.monitor.util.Formatter.getBundle().getText("ManufacturingOrderIsLate");break;default:return""}};
i2d.pp.prdorderissue.monitor.util.Formatter.leadingZeros=function(n){if(n){return n.replace(/^(0+)/g,'')};return""};
i2d.pp.prdorderissue.monitor.util.Formatter.formatRatioInPct=function(v,p){if((v!=null)&&(p!=null)){var f=sap.ca.ui.model.format.QuantityFormat.FormatQuantityStandard(v,p);return f+" "+"%"};return v+" "+"%"};
i2d.pp.prdorderissue.monitor.util.Formatter.formatNumberOfComponents=function(s){return(s=="0")?"None":"Error"};
i2d.pp.prdorderissue.monitor.util.Formatter.formatLatenessDuration=function(s){return"Error"};
i2d.pp.prdorderissue.monitor.util.Formatter.formatMaximumDelay=function(s){return"Error"};
i2d.pp.prdorderissue.monitor.util.Formatter.formatDurationToNextStatus=function(s){try{if(s>0){return"Error"}else{return"None"}}catch(e){return"None"}};
i2d.pp.prdorderissue.monitor.util.Formatter.formatDurationToNextStatusInDaysState=function(s){try{if(s<0){return"Error"}else{return"None"}}catch(e){return"None"}};
i2d.pp.prdorderissue.monitor.util.Formatter.formatDurationToNextStatusInDays=function(d){try{var v=parseFloat(d);if(v<-1){var p=v*-1;return i2d.pp.prdorderissue.monitor.util.Formatter.getBundle().getText("OverdueByDays",[p])}if(v===-1){var p=v*-1;return i2d.pp.prdorderissue.monitor.util.Formatter.getBundle().getText("OverdueByDay",[p])}if(v===0){return i2d.pp.prdorderissue.monitor.util.Formatter.getBundle().getText("Today",[d])}if(v===1){return i2d.pp.prdorderissue.monitor.util.Formatter.getBundle().getText("InDay",[d])}if(v>1){return i2d.pp.prdorderissue.monitor.util.Formatter.getBundle().getText("InDays",[d])}}catch(e){return"None"}};
i2d.pp.prdorderissue.monitor.util.Formatter.formatMfgOrderProblemCatIconStockReq=function(c){try{var v=c.substring(0,1);if(v=="1"){return"Error"}else{return"None"}}catch(e){return"None"}};
i2d.pp.prdorderissue.monitor.util.Formatter.formatMfgOrderProblemCatIconTree=function(c){try{var v=c.substring(1,2);if(v=="1"){return"Error"}else{return"None"}}catch(e){return"None"}};
i2d.pp.prdorderissue.monitor.util.Formatter.formatMfgOrderProblemCatIconGantt=function(c){try{var v=c.substring(2,3);if(v=="1"){return"Error"}else{return"None"}}catch(e){return"None"}};
i2d.pp.prdorderissue.monitor.util.Formatter.formatBaseMaterialDelayText=function(l){if(l>=2){return this.getModel('i18n').getResourceBundle().getText("MASTER_STATUS_BASE_MAT_MISSING_X_DAYS",[l])}else if(l===1){return this.getModel('i18n').getResourceBundle().getText("MASTER_STATUS_BASE_MAT_MISSING_ONE_DAYS")}else{return this.getModel('i18n').getResourceBundle().getText("MASTER_STATUS_BASE_MAT_MISSING_ON_TIME")}};
i2d.pp.prdorderissue.monitor.util.Formatter.formatMissingComponentsText=function(n){if(n>=2){return this.getModel('i18n').getResourceBundle().getText("MASTER_STATUS_X_COMPONENTS_MISSING",[n])}else if(n===1){return this.getModel('i18n').getResourceBundle().getText("MASTER_STATUS_ONE_COMPONENT_MISSING",[n])}else{return this.getModel('i18n').getResourceBundle().getText("MASTER_STATUS_NO_MISSING_COMPONENTS",[n])}};
i2d.pp.prdorderissue.monitor.util.Formatter.formatProcessDelayText=function(d){if(d>=2){return this.getModel('i18n').getResourceBundle().getText("MASTER_STATUS_DELAYED_BY_X_DAYS",[d])}else if(d===1){return this.getModel('i18n').getResourceBundle().getText("MASTER_STATUS_DELAYED_BY_ONE_DAY")}else{return this.getModel('i18n').getResourceBundle().getText("MASTER_STATUS_ON_SCHEDULE")}};
